### ISSUE TITLE
Variable price no definida

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_stock_picking#1]
Al crear un picking y validarlo, sale que la variable price no esta definida, esto en el archivo [stock_picking.py](https://github.com/dansanti/l10n_cl_stock_picking/blob/9.0/models/stock_picking.py#L402)

Que variable deberia ir ahi???. **rec.price_uni**t talvez

**Comment by dansanti** [comment]
hay algunos cambios que tengo que subir
