### ISSUE TITLE
Error al crear un nuevo cliente en punto de venta

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_stock_picking#10]
Al crear un nuevo cliente se obtiene este mensaje:
![image](https://user-images.githubusercontent.com/7775116/35255335-8636ca96-ffbc-11e7-9c23-77ec12e3bfe3.png)

Depurando, hay varios problemas:
1.- La funcion create_from_ui de  sii.activity.description no esta migrada a la nueva api, usa cr, uid, context
2.- en la parte de JS usas la funcion preventDefault que tambien esta desactualizada
3.- El principal problema creo que es que al crear un cliente, siempre se espera crear un nuevo giro, deberiamos cambiar este comportamiento, los giros no son algo que se deba estar creando con cada nuevo cliente, deberian ser un combo_box simplemente de seleccion. Los giros creo que los da el sii como una tabla, asi que deberia el modulo es crear esa data al instalarse dicho modulo, con eso no seria necesario estar creando giros cada vez que se crea clientes, y si fuera necesario crear un nuevo giro, deberia ser desde el backend por laa parte administrativa creeria. Actualmente no es posible seleccionar un giro existente, siempre sale el cuadro de texto para crear un nuevo giro.

**Comment by dansanti** [comment]
EN realidad lo que se pide es la glosa descriptiva del giro, por eso es relativa al cliente, puede o no haber dos o más glosas iguales, a diferencia de los actecos que están ya predefinidos, poner giros predefinidos, es algo que no volverá a estar , porque genera más problemas que soluciones ( las secretarias, después no saben qué poner, porque los clientes exigen poner lasglosas no los actecos)

**Comment by dansanti** [comment]
Admemás este issue no va acá, debe ir en pos

**Comment by celm1990** [comment]
Upsss, me pareció estar en el punto de venta jejeje, bueno voy a consultar lo q dices, pero me parece q te contradices en el diseño del backend, porque ahi es un campo m2o en donde se permite seleccionar otros giros si no estoy mal
En todo caso si es necesario abro otro bug pero en el repositorio correcto
