### ISSUE TITLE
Datos de Precios e impuestos no se pasan a picking cuando son desde compras

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_stock_picking#11]
En este commit 63506ccca2ef778e1f78ddecaecaac25613083dc introducen un nuevo campo, para no usar el mismo que trae odoo por defecto(q se usa para la valoracion de inventario), segun entiendo el proposito del nuevo campo es netamente informativo y para calculos de valores en las guias de remision.
Cuando se crea un picking desde ventas se pasan valores como precio unitario, descuentos, impuestos y funciona todo bien, pero cuando se crea un picking desde compras, ninguno de esos valores se pasa, de cierto modo podria tener sentido xq fueron diseñados para guias de remision, y no para albaranes de compra, pero la verdad es que confunden al usuario ver valores con precio 1. Entonces sugiero:

1. Pasar los valores correcctos cuando sean albaranes desde compras(de entrada) solo informativo

2.- Ocultar esos campos de precios cuando el picking no es una guia, asi en albaranes de compra no se vera y no causaria confusion

Podria ayudar con el punto 1 si estan deacuerdo????

**Comment by celm1990** [comment]
Adjunto imagenes que muestran lo confuso que podria ser:

_Ventas, pasan valores y se ve bien_
![image](https://user-images.githubusercontent.com/7775116/35534526-c49d73aa-050e-11e8-82cb-067760fb1478.png)

_Compras pasa precio unitario 1, nada que ver con la realidad(ni impuestos se pasan)_
![image](https://user-images.githubusercontent.com/7775116/35534552-e18f9c90-050e-11e8-969a-c70ee0ca95e8.png)

**Comment by dansanti** [comment]
HOla! de hecho lo que hay que hacer es ocultar esos campos para el caso de compras, ya que no aportan información, no son necesarios ahí, ni los vana llenar, porque ya llenaron en la copmra, ahí si importan

**Comment by celm1990** [comment]
Revisando el codigo, vi que si tenias soporte para pasar los datos desde compras al movimiento de stock solo que los impuestos no se pasaban bien como espera el ORM, en el PR corregi eso y quedaria solucionado, si aceptas el PR se cierra este bug.

**Comment by celm1990** [comment]
hecho merge se cierra bug
