### ISSUE TITLE
Error al actualizar modulo en V11

### ISSUE THREAD

**Issue by celm1990** [dansanti/l10n_cl_stock_picking#13]
Cada vez que se actualiza el modulo, en el log sale este error:
![image](https://user-images.githubusercontent.com/7775116/35882280-9ef8f90a-0b51-11e8-8cbb-6be7f949cf89.png)
Esto creo que es un mal diseño, ya que el [campo sii_document_class_id lo haces requerido a nivel de clase](https://github.com/dansanti/l10n_cl_stock_picking/blob/11.0/models/stock_picking.py#L212)(a nivel de SQL se hace requerido) pero no todas las bodegas van a tener ese campo, creeria que solo las bodegas tipo interno podrian requerir ese campo, pero bodegas tipo clientes o proveedores seria imnecesario que se llene ese campo.
Sugiero cambiar el required que esta a nivel de python, para ponerlo required a nivel de vista(de esta manera podriamos hacerlo requerido condicionalmente, solo para las bodegas tipo interno).
![image](https://user-images.githubusercontent.com/7775116/35882397-0e604488-0b52-11e8-97b0-7e5142786ca1.png)

**Comment by dansanti** [comment]
eso es porque un campo rquerido no tiene valor por defecto para registros ya existentes

**Comment by celm1990** [comment]
Claro, por eso se hizo el PR para q el campo sea requerido a nivel de vistas y no a nivel de clases, como se hizo merge, cierro el bug. Gracias
