### ISSUE TITLE
Solicitud: Agregar en el pedido de venta que se genere GD en stock

### ISSUE THREAD

**Issue by rapolebas** [dansanti/l10n_cl_stock_picking#16]
Sera posible agregar en el formulario de pedido de venta que se seleccione si el despacho sera con guía o solo una salida de stock desde antes.

no se si me explico, si es posible agregarlo genial o ayudarme con indicaciones de como aportarlo yo.

Saludos

**Comment by dansanti** [comment]
Antes de validar la guía deben marcar si será tributaria o no

**Comment by rapolebas** [comment]
Claro, lo entiendo lo que me referia era que ese ticket pueda venir ya marcado desde el pedido de venta si es que se necesita que ese pedido especifico tenga guia de despacho.
